### ISSUE TITLE
Update README for Wikipedia Pipeline

### ISSUE THREAD

**Issue by morillo** [databricks/delta-live-tables-notebooks#23]
In Wikipedia DLT Pipeline Step 4
```
%sql
-- Review the top referrers to Wikipedia's Apache Spark articles
SELECT * FROM wiki_demo.wiki_spark
```

the name of the table `wiki_spark` should be changed to`top_spark_referers` instead.

**Comment by chrishfish** [comment]
@morillo still an issue? @jodb and I can fix it
