### ISSUE TITLE
Unable to import dlt method

### ISSUE THREAD

**Issue by BalajiLoganathan** [databricks/delta-live-tables-notebooks#25]
I am getting error saying dlt method not found. 
Second question is do not find pipeline feature under jobs. Can you please help me how to resolve the issues.

**Comment by jacobdanovitch** [comment]
Both the AWS and Azure documentation says to contact a Databricks representative to get access to DLT, but there's no link provided to do so. How do we actually enable DLT in our workspace?

**Comment by chrishfish** [comment]
@BalajiLoganathan DLT code is currently not intended to be run on an interactive cluster. I'll close this out.

@jacobdanovitch please reach out to your designed account team. If you don't have one, email sales@databricks.com. Thanks!
