### ISSUE TITLE
CSV Source and Load to Snowflake ETL

### ISSUE THREAD

**Issue by codewithpatch** [databricks/delta-live-tables-notebooks#41]
Hello Databricks team,

I've been looking through Databricks DLT documentation and I'm having a hard time to find a solution.
Is it possible to use a CSV file as the data source for DLT or do I have to convert my CSV to JSON or Parquet as these are the only file formats that are currently in your demo and documentation.

I am aiming to create an ETL which ingest data from CSV/Excel files and Load the data to our datawarehouse in Snowflake.

I am looking to use Databricks DLT to do the transformations such as data cleaning and data validations.
Is this a possible thing to do using Databricks DLT?

Hoping for a response from the team.

Thanks!

**Comment by omar-98** [comment]
same problem but with SQL syntax

**Comment by omar-98** [comment]
how can we add options in delta live table (header...)

**Comment by chrishfish** [comment]
DLT can only write data to Delta tables. You'll need a secondary task using Databricks Workflows to write data to Snowflake afterwards.
