### ISSUE TITLE
read a csv file in sql code with header option in live table( not in streaming)

### ISSUE THREAD

**Issue by omar-98** [databricks/delta-live-tables-notebooks#46]
i had a issue can a read a csv file in sql syntax with header in option without using autoloader or python syntax

**Comment by omar-98** [comment]
![image](https://user-images.githubusercontent.com/63150423/176401102-c6d25ff7-ee81-4c87-adad-c766b4cf5442.png)

**Comment by omar-98** [comment]
![image](https://user-images.githubusercontent.com/63150423/176401481-81e7307f-e16c-45e5-8968-e96d260b5be3.png)

**Comment by chrishfish** [comment]
Only using the Cloud-files api, otherwise this isn't possible in SQL.
