### ISSUE TITLE
Issue with approxQuantile() or usage of List within a DLT

### ISSUE THREAD

**Issue by Trodenn** [databricks/delta-live-tables-notebooks#59]
HI,

 

I am tying to use the approxQuantile() function and populate a list that I made, yet somehow, whenever I try to run the code it's as if the list is empty and there are no values in it.

 

Code is written as below:
```
    @dlt.table(name = "customer_order_silver_v2")
    def capping_unitPrice_Qt():
        df = dlt.read("customer_order_silver")
        boundary_unit = [0,0]
        boundary_qty = [0,0]
        boundary_unit = df.select(col("UnitPrice")).approxQuantile('UnitPrice',[0.05,0.95], 0.25)
     
        boundary_qty = df.select(col("Quantity")).approxQuantile('Quantity',[0.05,0.95], 0.25)
     
     
        df = df.withColumn('UnitPrice', F.when(col('UnitPrice') > boundary_unit[1], boundary_unit[1])
                                           .when(col('UnitPrice') < boundary_unit[0], boundary_unit[0])
                                           .otherwise(col('UnitPrice')))
        
        df = df.withColumn('Quantity', F.when(col('Quantity') > boundary_qty[1], boundary_qty[1])
                                           .when(col('Quantity') < boundary_qty[0], boundary_qty[0])
                                           .otherwise(col('Quantity')))
                                              
        return df
```
 

The output that I get when running is below:

![Screenshot_20230130_053953](https://user-images.githubusercontent.com/48042375/215560942-191c49f4-973c-45ef-ae53-723d39905b85.png)

I am trying really hard to understand what is the issue and why whatever I do the list is just not getting populated. approxQuantile should be returning a list so it does not make sense that it does not work.

**Comment by chrishfish** [comment]
hi @Trodenn because approx quantiles is not a regular dataframe function, I think it may not work in DLT. If this is required functionality for you, can you reach out to your Databricks account rep and ask to talk to the DLT Product Managers? Thanks!
