### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by sugidwan** [databricks/delta-live-tables-notebooks#60]
I am attempting to utilize Databricks Delta Live Tables from a Python notebook. The initial step is to import the 'dlt' module, however, it fails and produces an error message that the module could not be found. Despite having a premium Databricks workspace and access to the new DLT Pipelines feature, 

I am still trying to determine if the 'import dlt' command will work in the notebook without having to run it as part of a pipeline, as this would complicate the process significantly.

**Comment by sheridan06** [comment]
from my understanding @sugidwan, you can't run a DLT notebook on general purpose compute.  Like, you can't spin up a cluster, attach your DLT notebook, and try to execute it. Rather, then only way that I'm aware of is to create the DLT notebook, then navigate to Workflows -> Delta Live Tables -> Create Pipeline, and then add your DLT notebook to the pipeline.  I've had tremendous success doing this
