### ISSUE TITLE
divvy-bike-demo location of data_generator.py 

### ISSUE THREAD

**Issue by MidnightRambo** [databricks/delta-live-tables-notebooks#64]
Where do i find the "data_generator.py" and "change-data-capture-example.sql" mentioned in the divvy bike demo? 

I cannot find it being mentioned in the history or anywhere else.

**Comment by chrishfish** [comment]
i think the readme is out of date and you don't need that anymore. but please try out the other demos, some are out of date and unmaintained. the CDC demos are the most up to date
