### ISSUE TITLE
Cannot find  "data_generator.py" and "change-data-capture-example.sql"

### ISSUE THREAD

**Issue by tracytrivas** [databricks/delta-live-tables-notebooks#66]
Where do I get a copy of these two files? I am going through the demo, and cannot locate this.

**Comment by ravi-databricks** [comment]
They are part of [dais_dlt_meta_runners](https://github.com/databrickslabs/dlt-meta/blob/main/dlt-meta-demo/demo/dais_dlt_meta_runners.dbc)

**Comment by chrishfish** [comment]
I believe you don't need these anymore, but this demo may be out of date and unmaintained. Please try out instead the CDC from snapshot demo

**Comment by tracytrivas** [comment]
ok lemme give that one a try. Thanks

-Tracy
