### ISSUE TITLE
Parameterize NYC Taxi sample

### ISSUE THREAD

**Issue by dennyglee** [databricks/delta-live-tables-notebooks#7]
* Parameterize the notebook for DB and user (or storage folder)
* Make the misc queries separate from the setup notebook
* Just have pre-setup notebook copy your H3 data directory? 

via Scott Crawford

**Comment by dennyglee** [comment]
Additional fixes which will include in this issue
-  Avoid specifying the schema and any unneeded options.
- Don’t specify the name if it's the same as the function name
- Update map_point_to_location and src_green_cab references to configurable directory (currently set to home directory)
- Add comment to all tables
- Replace `pipelines.metastore.tableName` with `target` as a *pipeline setting* which will automatically create the table in the target database when specified 
- drop event log (but keep expectations) 
via @marmbrus

**Comment by chrishfish** [comment]
@dennyglee @jodb let's resolve this

**Comment by jodb** [comment]
@dennyglee if this is still an issue, let me know and I can take care of it if you like

**Comment by dennyglee** [comment]
Closing this issue as the NYC Sample has been moved to a different repo.
