### ISSUE TITLE
Issue with read_kafka within a DLT using SQL

### ISSUE THREAD

**Issue by zmsoft** [databricks/delta-live-tables-notebooks#81]
Hi @fmunz ,

I am tying to use the read_kafka function and populate my arguments, yet somehow, whenever I try to run the code it doesn't recognize the function.

Code is written as below:
```
CREATE  OR REFRESH STREAMING LIVE TABLE kafka_events_sql
  COMMENT 'The data ingested from kafka topic'
  AS SELECT
    *
  FROM STREAM read_kafka(
    bootstrapServers => 'xxx.xxx.azure.confluent.cloud:9092', 
    subscribe => 'fitness-tracker',
    startingOffsets => 'earliest',
    `kafka.security.protocol` => 'SASL_SSL',
    `kafka.sasl.mechanism` => 'PLAIN',
    `kafka.sasl.jaas.config` => 'kafkashaded.org.apache.kafka.common.security.plain.PlainLoginModule required username="xxx" password="xxx";'
  );
```

The output that I get when running is below:

![image](https://github.com/databricks/delta-live-tables-notebooks/assets/8024438/86743684-3d81-4e3c-84fc-33690ded8612)

I am trying really hard to understand what is the issue and why this function wouldn't work no matter what i did.

**Comment by chrishfish** [comment]
@zmsoft is this still an issue? I think this may have been a preview feature and you tested before it rolled out
